# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=1024, unique=True)),
                ('title', models.TextField()),
                ('author', models.CharField(blank=True, default='', max_length=1024)),
                ('bodytext', models.TextField()),
                ('orig_html', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('short_name', models.CharField(db_index=True, max_length=256)),
                ('legacy_feed_id', models.CharField(blank=True, db_index=True, max_length=8)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScraperResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_time', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField()),
                ('added_count', models.PositiveSmallIntegerField(default=0)),
                ('error_count', models.PositiveSmallIntegerField(default=0)),
                ('total_count', models.PositiveSmallIntegerField(default=0)),
                ('output', models.TextField(blank=True)),
                ('news_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsarticles.NewsSource')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='news_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsarticles.NewsSource'),
        ),
    ]
