# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsarticles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='bodytext',
            new_name='body_text',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='last_modified',
            new_name='updated',
        ),
        migrations.RemoveField(
            model_name='newssource',
            name='legacy_feed_id',
        ),
    ]
